export  const color = [
    {
        id:1,
        name:'Կարմիր',
        color:'#FF0000'
    },
    {
        id:2,
        name:'Նարնջագույն',
        color:'#FF8000'
    },
    {
        id:3,
        name:'Դեղին',
        color:'#FFFF00'
    },
    {
        id:4,
        name:'Դեղնականաչ',
        color:'#80FF00'
    },
    {
        id:5,
        name:'Կանաչ',
        color:'#00FF00'
    },
    {
        id:6,
        name:'Զմրուխտ',
        color:'#00FF80'
    },
    {
        id:6,
        name:'Կապտականաչ',
        color:'#00FFFF'
    },
    {
        id:7,
        name:'Երկնագույն',
        color:'#0080FF'
    },
    {
        id:8,
        name:'Կապույտ',
        color:'#0000FF'
    },
    {
        id:9,
        name:'Մանուշակագույն',
        color:'#8000FF'
    },
    {
        id:10,
        name:'Բաց վարդագույն',
        color:'#FF00FF'
    },
    {
        id:11,
        name:'Վարդագույն',
        color:'#FF0080'
    }
]

export const body = [
    {
        id:1,
        name:'Ունիվերսալ'
    }
]
